/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import ControladorApp.ControladorMuro;
import ControladorApp.ControladorRadioButtonMuro;
import Modelo.Publicacion;
import Modelo.Usuario;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author SANGYG
 */
public class MiMuro extends javax.swing.JPanel {

    /**
     * Creates new form MiMuro
     */
    ControladorRadioButtonMuro c;
    ControladorMuro miMuro;

    public MiMuro(Usuario u) {

        //controlador que controla los eventos del radiobutton y nececita this
        //para poder acceder a los componentes de esta vista
        c = new ControladorRadioButtonMuro(this);
        initComponents();

        panel2();
        //controlador que controla la vista muro y le paso this
        //para poder editar lso componentes de esta vista
        miMuro = new ControladorMuro(this, u);
        panelCard(u);

    }

    public final void panelCard(Usuario u) {

        panelMuro1.setLayout(new CardLayout());

        PublicacionTextoView p = new PublicacionTextoView(miMuro, u);
        panelMuro1.add(p, "texto");
        PublicacionFotoView p2 = new PublicacionFotoView();
        panelMuro1.add(p2, "foto");
        //eventos a los que responde el radiobutton
        p.getRadioFoto().addActionListener(c);
        p2.getRadioTexto().addActionListener(c);
    }

    public final void panel2() {
        panelMuro2.setLayout(new BoxLayout(panelMuro2, BoxLayout.Y_AXIS));

    }

    public JPanel getPanelMuro1() {
        return panelMuro1;
    }

    public JPanel getPanelMuro2() {
        return panelMuro2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMuro1 = new javax.swing.JPanel();
        panelMuro2 = new javax.swing.JPanel();

        javax.swing.GroupLayout panelMuro1Layout = new javax.swing.GroupLayout(panelMuro1);
        panelMuro1.setLayout(panelMuro1Layout);
        panelMuro1Layout.setHorizontalGroup(
            panelMuro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        panelMuro1Layout.setVerticalGroup(
            panelMuro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelMuro2Layout = new javax.swing.GroupLayout(panelMuro2);
        panelMuro2.setLayout(panelMuro2Layout);
        panelMuro2Layout.setHorizontalGroup(
            panelMuro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelMuro2Layout.setVerticalGroup(
            panelMuro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMuro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelMuro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelMuro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMuro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelMuro1;
    private javax.swing.JPanel panelMuro2;
    // End of variables declaration//GEN-END:variables
}
