/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import ControladorApp.ControladorMuro;
import Modelo.Publicacion;
import Modelo.Usuario;
import com.ieschirinos.dam.hsqlchiribook.ImageConverter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author SANGYG
 */
public class PublicacionFotoView extends javax.swing.JPanel {

    Publicacion p;
    Usuario u;
    ControladorMuro controladorM;
       ImageIcon icon;

    /**
     * Creates new form PublicacionFotoView
     * @param c
     * @param u
     */
    public PublicacionFotoView(ControladorMuro c, Usuario u) {
        this.controladorM=c;
        this.u=u;
        initComponents();
    }
    public JButton getBtComentar() {
        return btComentar;
    }

    public void setBtComentar(JButton btComentar) {
        this.btComentar = btComentar;
    }

    public JButton getBtExaminar() {
        return btExaminar;
    }

    public void setBtExaminar(JButton btExaminar) {
        this.btExaminar = btExaminar;
    }

    public JLabel getFotoPublicacion() {
        return fotoPublicacion;
    }

    public void setFotoPublicacion(JLabel fotoPublicacion) {
        this.fotoPublicacion = fotoPublicacion;
    }

    public JRadioButton getRadioTexto() {
        return radioTexto;
    }

    public void setRadioTexto(JRadioButton radioTexto) {
        this.radioTexto = radioTexto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btComentar = new javax.swing.JButton();
        btExaminar = new javax.swing.JButton();
        radioTexto = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fotoPublicacion = new javax.swing.JLabel();

        btComentar.setText("comentar");
        btComentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComentarActionPerformed(evt);
            }
        });

        btExaminar.setText("examinar");
        btExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExaminarActionPerformed(evt);
            }
        });

        radioTexto.setText("texto");

        fotoPublicacion.setText("foto");
        jScrollPane1.setViewportView(fotoPublicacion);
        fotoPublicacion.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btExaminar)
                    .addComponent(btComentar)
                    .addComponent(radioTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btExaminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btComentar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioTexto))
            .addComponent(jScrollPane1)
        );

        btComentar.getAccessibleContext().setAccessibleName("btcomentar");
        btExaminar.getAccessibleContext().setAccessibleName("btexaminar");
        radioTexto.getAccessibleContext().setAccessibleName("radioTexto");
    }// </editor-fold>//GEN-END:initComponents

    private void btComentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComentarActionPerformed
        // TODO add your handling code here:
            // Cambiar FOTO
       controladorM.crearPublicacionFoto(icon, u);

    }//GEN-LAST:event_btComentarActionPerformed

    private void btExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExaminarActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        if(jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = jfc.getSelectedFile();
            try {
             icon = new ImageIcon(f.toURL());
                 fotoPublicacion.setIcon(icon);
                controladorM.recibeImagen(icon);
               
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_btExaminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btComentar;
    private javax.swing.JButton btExaminar;
    private javax.swing.JLabel fotoPublicacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioTexto;
    // End of variables declaration//GEN-END:variables
}
