/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import ControladorApp.ControladorMuro;
import Modelo.Publicacion;
import Modelo.Texto;
import Modelo.Usuario;
import java.awt.CardLayout;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextPane;

/**
 *
 * @author SANGYG
 */
public class PublicacionTextoView extends javax.swing.JPanel {

    /**
     * Creates new form PublicacionMiMuro
     */
    Publicacion p;
    Usuario u;
    ControladorMuro controladorM;
    String mensaje;
    ResourceBundle bundle;

    public PublicacionTextoView(ControladorMuro c, Usuario u, ResourceBundle bundle) {
        this.bundle = bundle;
        this.controladorM = c;
        this.u = u;
        initComponents();
        btComentar.setText(bundle.getString("comentar"));
        radioFoto.setText(bundle.getString("foto"));
        obtenerTexto();
        btComentarComentario.setVisible(false);
    }

    public final void obtenerTexto() {

        btComentar.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                mensaje = texto.getText();
                if (mensaje.isEmpty()) {
                    jLError.setText(bundle.getString("error"));
                } else {
                    controladorM.crearPublicacionTexto(mensaje, u);
                    texto.setText("");
                    jLError.setText("");
                }
            }
        });
    }

    public JButton getBtComentar() {
        return btComentar;
    }

    public void setBtComentar(JButton btComentar) {
        this.btComentar = btComentar;
    }

    public JRadioButton getRadioFoto() {
        return radioFoto;
    }

    public void setRadioFoto(JRadioButton radioFoto) {
        this.radioFoto = radioFoto;
    }

    public JTextPane getTexto() {
        return texto;
    }

    public void setTexto(JTextPane texto) {
        this.texto = texto;
    }
    public void desactivarActivarComentar(){
    this.btComentar.setEnabled(false);
    this.btComentar.setVisible(false);
    this.btComentarComentario.setEnabled(true);
    this.btComentarComentario.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextPane();
        radioFoto = new javax.swing.JRadioButton();
        btComentar = new javax.swing.JButton();
        jLError = new javax.swing.JLabel();
        btComentarComentario = new javax.swing.JButton();

        jScrollPane2.setViewportView(texto);

        radioFoto.setText("FOTO");

        btComentar.setText("comentar");

        btComentarComentario.setText("Comentar");
        btComentarComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComentarComentarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLError, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btComentarComentario)
                            .addComponent(btComentar)
                            .addComponent(radioFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 124, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLError, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btComentar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btComentarComentario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioFoto)))
                .addGap(25, 25, 25))
        );

        radioFoto.getAccessibleContext().setAccessibleName("radioFoto");
        btComentar.getAccessibleContext().setAccessibleName("btComentar");
    }// </editor-fold>//GEN-END:initComponents

    private void btComentarComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComentarComentarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btComentarComentarioActionPerformed

    public JButton getBtComentarComentario() {
        return btComentarComentario;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btComentar;
    private javax.swing.JButton btComentarComentario;
    private javax.swing.JLabel jLError;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radioFoto;
    private javax.swing.JTextPane texto;
    // End of variables declaration//GEN-END:variables
}
