/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaLoginApp;

import ControladorLogin.ControladorLogin;
import DAO.UtilConnectionHSQL;
import Modelo.Usuario;
import Vistas.VistaPrincipal;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author SANGYG
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    ValidacionComponentesLogin validacion;
    ControladorLogin controladorLogin;

    public Login() {
        initComponents();
        validacion = new ValidacionComponentesLogin(this);
        controladorLogin = new ControladorLogin(this);
        comprobarcamposVacios();
        iniciarSesion();
    }

    public final void comprobarcamposVacios() {
        this.jtNombre.setInputVerifier(validacion);
        this.jtPass.setInputVerifier(validacion);
    }

    /**
     * Metodo que inicia sesion en la aplicacion si existe el usuario
     */
    public final void iniciarSesion() {
        btConectar.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Usuario a = controladorLogin.buscarUsuario();
                if (a == null) {
                    jLabel1.setText("No existe el usuario");
                } else {

                    jLabel1.setText("Usuario encontrado");
                    VistaPrincipal v = new VistaPrincipal(a);

                }

            }
        });
    }

    public JButton getBtAltaUsuario() {
        return btAltaUsuario;
    }

    public void setBtAltaUsuario(JButton btAltaUsuario) {
        this.btAltaUsuario = btAltaUsuario;
    }

    public JButton getBtConectar() {
        return btConectar;
    }

    public void setBtConectar(JButton btConectar) {
        this.btConectar = btConectar;
    }

    public JLabel getErrorNombre() {
        return errorNombre;
    }

    public void setErrorNombre(JLabel errorNombre) {
        this.errorNombre = errorNombre;
    }

    public JLabel getErrorPass() {
        return errorPass;
    }

    public void setErrorPass(JLabel errorPass) {
        this.errorPass = errorPass;
    }

    public JLabel getJlabelNombre() {
        return jlabelNombre;
    }

    public void setJlabelNombre(JLabel jlabelNombre) {
        this.jlabelNombre = jlabelNombre;
    }

    public JLabel getJlabelPass() {
        return jlabelPass;
    }

    public void setJlabelPass(JLabel jlabelPass) {
        this.jlabelPass = jlabelPass;
    }

    public JTextField getJtNombre() {
        return jtNombre;
    }

    public void setJtNombre(JTextField jtNombre) {
        this.jtNombre = jtNombre;
    }

    public JPasswordField getJtPass() {
        return jtPass;
    }

    public void setJtPass(JPasswordField jtPass) {
        this.jtPass = jtPass;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabelNombre = new javax.swing.JLabel();
        jlabelPass = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jtPass = new javax.swing.JPasswordField();
        btConectar = new javax.swing.JButton();
        btAltaUsuario = new javax.swing.JButton();
        errorNombre = new javax.swing.JLabel();
        errorPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlabelNombre.setText("Nombre :");

        jlabelPass.setText("Contraseña: ");

        jLabel1.setText("jLabel1");

        btConectar.setText("CONECTAR");

        btAltaUsuario.setText("Nuevo Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btConectar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlabelPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btAltaUsuario)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtNombre)
                                        .addComponent(jtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(errorNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(errorPass, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabelPass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(errorPass, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConectar)
                    .addComponent(btAltaUsuario))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAltaUsuario;
    private javax.swing.JButton btConectar;
    private javax.swing.JLabel errorNombre;
    private javax.swing.JLabel errorPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlabelNombre;
    private javax.swing.JLabel jlabelPass;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JPasswordField jtPass;
    // End of variables declaration//GEN-END:variables
}
